spring.datasource.url=jdbc:postgresql://dpg-d75l88n5r7bs738leoqg-a:5432/faculty_db_u50i
spring.datasource.username=faculty_db_u50i_user
spring.datasource.password=YwZubFivcTrK9DkFaO31fV6mYMgtTytX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080